# Generated by Django 4.2.11 on 2024-05-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='AddarNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Yearsofexperience',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
